# Generated by Django 4.2.6 on 2023-12-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='institucion',
            name='direccion_institucion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='nombre_institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='telefono_institucion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
